# Generated by Django 3.2.4 on 2021-06-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210630_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aes_key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
